### PR TITLE
PR for design teardown project

### PR DESCRIPTION
**Pull request by bettercallazamat**
## In this project we managed to do the following:
1. Create semantic elements with dummy text, but right positioning and sizes
2. Work on font-size and font-weight to make some of the text higher in the visual hierarchy
3. Apply different shades of gray to elements (from darker to lighter shades in descending order of visual hierarchy)

### CODE REVIEW

**Comment by uryelah** [comment]
Hello **Azamat Nuriddinov** & **Franco Rosa Alagón**, I'm Sarah, your reviewer for this PR 👩‍🚀 

First of all, you did an amazing job with this project! 🎊 🚀 

**Great job at:** 🥇
- making a very professional readme file and PR message
- writing tidy CSS with descriptive class names
-  paying attention to font size and weight
- having a great understanding of visual hierarchy
- making a beautiful footer. (Really, it looks great 🏅 )

**You still need to work on a couple of details before you can move on to the next project though**
-----

### Required changes 🛠 
### 

article_requirement

1.  **Semantic HTML ([read more on it here](https://www.w3schools.com/html/html5_semantic_elements.asp))**
Most `<div>`s with class ending at `article` should actually be `<article>` elements.

Top 2 article rows of the page
- [ ] Each has to contain **2 articles**, each takes 1/2 of the width. Please change the '<div class='main-article'>`s to article elements.

Mid 3 article rows
- [ ] Each has to contain **3 articles**, each takes 1/3 of the width. Please change the '<div class='post-article'>`s to article elements.

1 article rows
- [ ] Each has to contain **1 article**, each takes 1/1 of the width. Please change `div`s to which this applies to `article`s.

-------

**Please fix the required changes 👷  before asking for a new code review**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @bettercallazamat       
#### Great Job so far, but there is one more thing required. 
### General
#### Mid 3 article rows

- [ ]  It contains 3 articles, each takes one third of the width . Yours has four.




### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by majovanilla** [comment]
# Code Review in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
## Good job implementing the changes on this project! 👍

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some warnings. Please fix them. In this case, is about the lack of heading inside your sections. The ideal would be to use a different tag if you are not going to include titles.

## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by MarioDena** [comment]
Hello! Congratulations on your project!

You fixed and implemented the requested changes, 
## this project is approved!!

## Code review by Mario Enrique Delgado Naranjo

**Comment by bettercallazamat** [comment]
test 1

**Comment by bettercallazamat** [comment]
test

**Comment by bettercallazamat** [comment]
test

**Comment by bettercallazamat** [comment]
test

**Comment by bettercallazamat** [comment]
test

**Comment by bettercallazamat** [comment]
test

**Comment by bettercallazamat** [comment]
test

**Comment by bettercallazamat** [comment]
test

**Pull request merged**
